name: 'Clover to ShieldsIO endpoint JSON'
description: 'Generates a ShieldsIO endpoint compatible JSON file containing the code coverage from a clover.xml'
inputs:
  path-to-clover:
    description: 'Relative path from repository root to clover.xml'
    required: true
    default: 'clover.xml'
  path-to-json:
    description: 'Relative path from repository root where ShieldsIO endpoint JSON is created'
    required: true
    default: 'shieldsio.json'
  label-text:
    description: 'The left text of the badge; empty to omit left side'
    default: 'coverage'
  style:
    description: 'The badge style'
    default: 'flat'
  bad-threshold:
    description: 'Below this coverage percent, the color will be bad-color'
    default: 50
  average-threshold:
    description: 'Below this coverage percent, the color will be average-color'
    default: 75
  above-average-threshold:
    description: 'Below this coverage percent, the color will be above-average-color'
    default: 95
  bad-color:
    description: 'The color used for bad code coverage'
    default: 'red'
  average-color:
    description: 'The color used for average code coverage'
    default: 'yellow'
  above-average-color:
    description: 'The color used for above average code coverage'
    default: 'green'
  good-color:
    description: 'The color used for good code coverage'
    default: 'brightgreen'
runs:
  using: 'node12'
  main: 'dist/index.js'
